'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CurrencyConverter
    
    '''<summary>
    '''tbCurrencyIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCurrencyIn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlcurrencytype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcurrencytype As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnConvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConvert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblCurrencyOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrencyOut As Global.System.Web.UI.WebControls.Label
End Class
