<%@ Page Title="" Language="VB" MasterPageFile="~/Layout.master" AutoEventWireup="false" CodeFile="ViewCart.aspx.vb" Inherits="ViewCart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <meta http-equiv="Refresh" content="5" />  
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="content" Runat="Server">
    <div class="breadcrumbs">
		<ol class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li class="active">Shopping Cart</li>
		</ol>
	</div>

    <form runat="server">
        

    <asp:SqlDataSource ID="sqlDSCart2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionStringOnlineStore %>"> 
    </asp:SqlDataSource>
       
    <asp:ListView ID="lvCart" runat="server" DataSourceID="sqlDSCart2"
        OnItemCommand="lvCart_OnItemCommand" CellPadding="3" DataKeyField="CartNo,WebID"
        CellSpacing="0" RepeatColumns="1" DataKeyNames="CartID">
        <LayoutTemplate>              
            <div style="float: right; margin: 0 30px 5px 0;">
                <asp:Label ID="lblPage" runat="server" Text="" Font-Size="14px"></asp:Label>
            </div><br />
 	        <div class="table-responsive cart_info">
		    <table class="table table-condensed">
			    <thead>
				    <tr class="cart_menu">
					    <td class="image">Item</td>
					    <td class="description"></td>
					    <td class="price">Price</td>
					    <td class="quantity">Quantity</td>
					    <td class="total">Total</td>
					    <td></td>
				    </tr>
			    </thead>
			    <tbody>
                    <asp:PlaceHolder runat="server" ID="groupPlaceHolder" />
                </tbody>
            </table>                     
        </LayoutTemplate>
        <GroupTemplate>
            <asp:PlaceHolder runat="server" id="itemPlaceholder"></asp:PlaceHolder>
        </GroupTemplate>
        <ItemTemplate>
			<tr>
				<td class="cart_product">
					<img src="images/product/<%# Trim(Eval("WebID")) %>.jpg" width="150" alt="" />
				</td>
				<td class="cart_description">
					<h4><%# Eval("ProductName") %></h4>
					<p>Web ID: <%# Eval("WebID") %></p>
				</td>
				<td class="cart_price">
					<p>$<%# Eval("Price") %></p>
				</td>
				<td class="cart_quantity">
					<div class="cart_quantity_button">
                       <asp:TextBox ID="tbQuantity" Text='<%# Eval("Quantity")%>' Width="50px" CssClass="" runat="server"></asp:TextBox>
                       <asp:LinkButton runat="server" ID="lbUpdate" Text='Update'
                            CommandName="cmdUpdate" CommandArgument='<%# Eval("WebID")%>' />                  
					</div>
				</td>
				<td class="cart_total">
			<asp:Label id="total"  Text='<%# Eval("Quantity") * Eval("Price") %>' runat="server">
                 <p>$<%# Eval("Quantity") * Eval("Price") %></p>
			</asp:Label>
				</td>
				<td class="cart_delete">
                    <asp:LinkButton runat="server" ID="lbDelete" Text='Delete' 
                            CommandName="cmdDelete" CommandArgument='<%# Eval("WebID")%>' />
				</td>
			</tr>
            
        </ItemTemplate>
    </asp:ListView>
         <asp:Label ID="Label1" runat="server"></asp:Label>
    <asp:Button runat="server" ID="btnDel" Text="Delete All Cart" cssclass="btn btn-fefault cart"/>
    <div style="padding: 8px;width: 100%;text-align: center;">
        <div style="display: inline-block; margin-top: 5px">
        <asp:Button runat="server" Text="&laquo;" id="show_prev" CssClass="show_prevx"></asp:Button>
        <asp:DataPager ID="DataCart" runat="server" PagedControlID="lvCart" PageSize="3">
            <Fields>        
            <asp:NumericPagerField NextPageText='&raquo;' PreviousPageText='&laquo;' ButtonCount="5" 
                ButtonType="Button" NextPreviousButtonCssClass="next_prevx" NumericButtonCssClass="numericx" 
                CurrentPageLabelCssClass="currentx" RenderNonBreakingSpacesBetweenControls="False" />
            </Fields>
        </asp:DataPager>
        <asp:Button runat="server" Text="&raquo;" id="show_next" CssClass="show_nextx"></asp:Button>
    </div>



    <asp:SqlDataSource ID="SqlDSCart1" runat="server" 
        DataSourceMode="DataSet"
        ConnectionString="<%$ ConnectionStrings:ConnectionStringOnlineStore %>" 
        SelectCommand=""
        DeleteCommand="DELETE FROM [Cart] WHERE ([CartNo] = @CartNo AND [WebID] = @WebID)"
        UpdateCommand="UPDATE [Cart] SET [Quantity] = @Quantity WHERE ([CartNo] = @CartNo AND [WebID] = @WebID)">
        
    </asp:SqlDataSource>
    <asp:GridView ID="gvCart" runat="server" AutoGenerateColumns="False" 
        DataSourceID="SqlDSCart1" AllowPaging="True" PageSize="3" DataKeyNames="CartNo,WebID"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        EmptyDataText="There is no product in the cart." ShowFooter="True">
        <Columns>
            <asp:BoundField DataField="WebID" HeaderText="Web ID" InsertVisible="False" ReadOnly="true"
                SortExpression="WebID" />
            <asp:BoundField DataField="ProductName" HeaderText="Product Name" InsertVisible="False" ReadOnly="true"
                SortExpression="ProductName" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" 
                SortExpression="Quantity" />
            
            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" InsertVisible="False" ReadOnly="true" />
            <asp:TemplateField HeaderText="TotalText">
                <ItemTemplate>
                    <asp:Label ID="TotalLabel" runat="server" Text='<%# Eval("Quantity") * Eval("Price") %>'>
                    </asp:Label>                   
                </ItemTemplate>
                <FooterTemplate>
     <asp:Label ID="lblTotal" runat="server"></asp:Label>

     </FooterTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BorderColor="Red" BorderStyle="Dotted" />
    </asp:GridView>


        </div>
	</form>
</asp:Content>

